# Generated by Django 4.2.7 on 2025-07-21 20:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user_message", "User Message"),
                            ("assistant_response", "Assistant Response"),
                            ("system_message", "System Message"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_message", models.TextField(blank=True)),
                ("assistant_response", models.TextField(blank=True)),
                (
                    "message_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "openai_model",
                    models.CharField(default="gpt-3.5-turbo", max_length=50),
                ),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("conversation_turn", models.IntegerField(default=1)),
                ("conversation_history", models.JSONField(default=list)),
                ("user_input_length", models.IntegerField(default=0)),
                ("response_length", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("interaction_quality_score", models.FloatField(blank=True, null=True)),
                ("contains_question", models.BooleanField(default=False)),
                ("contains_code", models.BooleanField(default=False)),
                ("contains_linux_command", models.BooleanField(default=False)),
                ("topic_category", models.CharField(blank=True, max_length=100)),
                ("api_request_id", models.CharField(blank=True, max_length=100)),
                ("rate_limit_hit", models.BooleanField(default=False)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["message_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("chat_ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_chat_duration_seconds", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("total_user_messages", models.IntegerField(default=0)),
                ("total_assistant_responses", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("total_prompt_tokens", models.IntegerField(default=0)),
                ("total_completion_tokens", models.IntegerField(default=0)),
                ("average_response_time_ms", models.FloatField(default=0.0)),
                ("longest_response_time_ms", models.IntegerField(default=0)),
                ("shortest_response_time_ms", models.IntegerField(default=0)),
                ("total_user_characters", models.IntegerField(default=0)),
                ("total_assistant_characters", models.IntegerField(default=0)),
                ("average_message_length", models.FloatField(default=0.0)),
                ("questions_asked", models.IntegerField(default=0)),
                ("code_discussions", models.IntegerField(default=0)),
                ("linux_command_queries", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "total_estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("rate_limit_hits", models.IntegerField(default=0)),
                ("total_retries", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-chat_started_at"],
            },
        ),
    ]
