# Generated by Django 4.2.7 on 2025-07-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("studies", "0001_initial"),
        ("chats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_session",
                to="studies.studysession",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatinteraction",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_interactions",
                to="studies.studysession",
            ),
        ),
        migrations.AddField(
            model_name="chatinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatinteraction",
            index=models.Index(
                fields=["session", "message_timestamp"],
                name="chats_chati_session_91bc65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatinteraction",
            index=models.Index(
                fields=["user", "message_timestamp"],
                name="chats_chati_user_id_855078_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatinteraction",
            index=models.Index(
                fields=["message_type"], name="chats_chati_message_ced6c4_idx"
            ),
        ),
    ]
