# Generated by Django 4.2.7 on 2025-07-17 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("study_group", models.CharField(default="PDF", max_length=10)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PDFSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pdf_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("pdf_ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_session_duration_seconds", models.IntegerField(default=0)),
                ("active_reading_time_seconds", models.IntegerField(default=0)),
                ("idle_time_seconds", models.IntegerField(default=0)),
                ("pages_visited", models.JSONField(default=list)),
                ("unique_pages_visited", models.IntegerField(default=0)),
                ("total_page_views", models.IntegerField(default=0)),
                ("reading_completion_percentage", models.FloatField(default=0.0)),
                ("total_interactions", models.IntegerField(default=0)),
                ("scroll_interactions", models.IntegerField(default=0)),
                ("zoom_interactions", models.IntegerField(default=0)),
                ("search_interactions", models.IntegerField(default=0)),
                ("average_time_per_page_seconds", models.FloatField(default=0.0)),
                ("longest_page_time_seconds", models.FloatField(default=0.0)),
                ("shortest_page_time_seconds", models.FloatField(default=0.0)),
                ("text_selections", models.IntegerField(default=0)),
                ("annotations_made", models.IntegerField(default=0)),
                ("searches_performed", models.IntegerField(default=0)),
                ("forward_navigation_count", models.IntegerField(default=0)),
                ("backward_navigation_count", models.IntegerField(default=0)),
                ("jump_navigation_count", models.IntegerField(default=0)),
                ("focus_changes", models.IntegerField(default=0)),
                ("times_returned_to_pdf", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="pdfs.pdfdocument",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_session",
                        to="studies.studysession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pdf_started_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("scroll", "Scroll"),
                            ("zoom", "Zoom"),
                            ("search", "Search"),
                            ("highlight", "Highlight"),
                            ("annotation", "Annotation"),
                            ("download", "Download"),
                            ("print", "Print"),
                            ("navigate", "Navigate"),
                            ("resize", "Resize"),
                            ("fullscreen", "Fullscreen"),
                            ("copy_text", "Copy Text"),
                            ("bookmark", "Bookmark"),
                            ("session_start", "Session Start"),
                            ("session_end", "Session End"),
                            ("idle_detected", "Idle Detected"),
                            ("focus_lost", "Focus Lost"),
                            ("focus_gained", "Focus Gained"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("total_pages", models.IntegerField(blank=True, null=True)),
                ("viewport_width", models.IntegerField(blank=True, null=True)),
                ("viewport_height", models.IntegerField(blank=True, null=True)),
                ("scroll_x", models.IntegerField(blank=True, null=True)),
                ("scroll_y", models.IntegerField(blank=True, null=True)),
                ("zoom_level", models.FloatField(blank=True, null=True)),
                ("time_on_page_seconds", models.FloatField(blank=True, null=True)),
                ("cumulative_time_seconds", models.FloatField(default=0.0)),
                ("search_query", models.CharField(blank=True, max_length=200)),
                ("highlighted_text", models.TextField(blank=True)),
                ("annotation_text", models.TextField(blank=True)),
                ("copied_text", models.TextField(blank=True)),
                ("reading_speed_wpm", models.FloatField(blank=True, null=True)),
                ("dwell_time_ms", models.IntegerField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("screen_resolution", models.CharField(blank=True, max_length=20)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="pdfs.pdfdocument",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_interactions",
                        to="studies.studysession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="pdfs_pdfint_session_faa4b0_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="pdfs_pdfint_user_id_befb6f_idx",
                    ),
                    models.Index(
                        fields=["document", "timestamp"],
                        name="pdfs_pdfint_documen_d6986e_idx",
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="pdfs_pdfint_interac_a58995_idx",
                    ),
                    models.Index(
                        fields=["page_number"], name="pdfs_pdfint_page_nu_34ccd3_idx"
                    ),
                ],
            },
        ),
    ]
