# Generated by Django 4.2.7 on 2025-07-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="transfer_quiz_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="transfer_quiz_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
