# Generated by Django 4.2.7 on 2025-07-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(max_length=100, unique=True)),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("consent", "Consent"),
                            ("pre_quiz", "Pre-Quiz"),
                            ("interaction", "Interaction"),
                            ("post_quiz", "Post-Quiz"),
                            ("completed", "Completed"),
                        ],
                        default="consent",
                        max_length=20,
                    ),
                ),
                (
                    "session_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("session_ended_at", models.DateTimeField(blank=True, null=True)),
                ("consent_started_at", models.DateTimeField(blank=True, null=True)),
                ("consent_ended_at", models.DateTimeField(blank=True, null=True)),
                ("pre_quiz_started_at", models.DateTimeField(blank=True, null=True)),
                ("pre_quiz_ended_at", models.DateTimeField(blank=True, null=True)),
                ("interaction_started_at", models.DateTimeField(blank=True, null=True)),
                ("interaction_ended_at", models.DateTimeField(blank=True, null=True)),
                ("post_quiz_started_at", models.DateTimeField(blank=True, null=True)),
                ("post_quiz_ended_at", models.DateTimeField(blank=True, null=True)),
                ("consent_duration", models.IntegerField(default=0)),
                ("pre_quiz_duration", models.IntegerField(default=0)),
                ("interaction_duration", models.IntegerField(default=0)),
                ("post_quiz_duration", models.IntegerField(default=0)),
                ("total_duration", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-session_started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("session_start", "Session Start"),
                            ("session_end", "Session End"),
                            ("study_joined", "Study Joined"),
                            ("phase_start", "Phase Start"),
                            ("phase_end", "Phase End"),
                            ("page_view", "Page View"),
                            ("button_click", "Button Click"),
                            ("form_submit", "Form Submit"),
                            ("chat_message", "Chat Message"),
                            ("quiz_answer", "Quiz Answer"),
                            ("quiz_start", "Quiz Start"),
                            ("quiz_submit", "Quiz Submit"),
                            ("pdf_view", "PDF View"),
                            ("pdf_scroll", "PDF Scroll"),
                            ("pdf_interaction", "PDF Interaction"),
                            ("time_spent", "Time Spent"),
                            ("system_event", "System Event"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_data", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="studies.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "log_type"],
                        name="studies_stu_session_529f32_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="studies_stu_timesta_ac6404_idx"
                    ),
                ],
            },
        ),
    ]
