# Generated by Django 4.2.7 on 2025-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studysession",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="studylog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("study_joined", "Study Joined"),
                    ("phase_start", "Phase Start"),
                    ("phase_end", "Phase End"),
                    ("page_view", "Page View"),
                    ("button_click", "Button Click"),
                    ("form_submit", "Form Submit"),
                    ("chat_message", "Chat Message"),
                    ("quiz_answer", "Quiz Answer"),
                    ("quiz_start", "Quiz Start"),
                    ("quiz_submit", "Quiz Submit"),
                    ("pdf_view", "PDF View"),
                    ("pdf_scroll", "PDF Scroll"),
                    ("pdf_interaction", "PDF Interaction"),
                    ("time_spent", "Time Spent"),
                    ("system_event", "System Event"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
