[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "mkdir -p logs",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn research_platform.wsgi:application --bind 0.0.0.0:$PORT"