[deploy]
startCommand = "python manage.py migrate && gunicorn research_platform.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "research_platform.settings_production" }