[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd research-study-platform/backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn research_platform.wsgi:application"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "research_platform.settings_production" }